@startuml Backend

' !theme mars from https://raw.githubusercontent.com/plantuml/plantuml/master/themes

' TODO:All the controllers

' This is not gonna be a table
abstract class User {
  -String username
  -String emailAddress
  -String userId
  -String phoneNumber
  -String password

  +String getUsername()
  +String getPhoneNumber()
  +String getUserId()
  +String getEmailAddress()
  +String getPassword()
  +String setUsername()
  +String setPhoneNumber()
  +String setUserId()
  +String setEmailAddress()
  +String setPassword()
}

' Need to check this
' For now this is a table too
' TODO:What do with the methods?
class Manager Extends User{
  ' +void addItems()
  ' +void removeItems()
  ' +void generateReports()
}

' This extends JPA repository
interface ManagerRepository{
  +ArrayList<Manager> findAll()
  +Manager findByEmail()
  +void save()
  +void deleteById()

}

' TODO:Same as manager what do?
class Admin Extends User{
  ' +void addManager()
  ' +void deleteManager()
}

' This extends JPA repository
interface AdminRepository {
  +ArrayList<Admin> findAll()
  +Admin findByEmail()
  +void save()
  +void deleteById()
}

' Need to check this
class Customer Extends User{
  -float moneyInWallet
  -Cart cart

  +float getMoneyInWallet()
  +ArrayList<HashMap<Product, Integer>> getProductsInCart()
  +void setMoneyInWallet()
  +void setProductsInCart() 
}

class Cart {
  -ArrayList<HashMap<Product, Integer>> productsWithQuantity
  -int totalPrice
  -int totalItems

  +ArrayList<HashMap<Product, Integer>> getProductsInCartWithQuantity()
  +int getTotalPrice()
  +int getTotalItemCount()
  +ArrayList<HashMap<Product, Integer>> addItemToCart()
  +ArrayList<HashMap<Product, Integer>> removeItemFromCart()
  +ArrayList<HashMap<Product, Integer>> emptyCart()
}

Customer *-- Cart

' This extends JPA repository
interface CustomerRepository{
  +ArrayList<Customer> findAll()
  +Customer findByEmail()
  +void save()
  +void deleteById()
  +void addItemToCart()
  +void removeItemFromCart()
  +int getTotalItemCount()
  +int getTotalCartCost()
  +boolean isMoneyInWalletEmpty()
  +void updateMoneyInWallet()
  +Order getOrder()
  +ArrayList<Order> getAllOrders()
}

class CustomerController {
  -CustomerRepository customerRepository
  
  +ArrayList<Customer> getAllCustomers()
  +Customer getCustomer()
  +void createCustomerAccount()
  +void deleteCustomerAccount()
  +void updateCustomerAccount()
  +void addItemToCart()
  +void removeItemFromCart()
  +int getTotalItemCount()
  +int getTotalCartCost()
  +boolean isMoneyInWalletEmpty()
  +void updateMoneyInWallet()
  +Order getOrder()
  +ArrayList<Order> getAllOrders()
}

' This extends JPA repository
interface CartRepository {
  +Cart getCart()
  +int getTotalPrice()
  +int getTotalItemCount()
  +void addItemToCart()
  +void removeItemFromCart()
  +void emptyCart()
}

class CartController {
  -CartRepository CartRepository

  +Cart getCart()
  +int getTotalPrice()
  +int getTotalItemCount()
  +void addItemToCart()
  +void removeItemFromCart()
  +void emptyCart()
}

' This extends "UserDetails" from spring security
' TODO:Login shite
class UserDetails {
  -User user
	+String getPassword()
	+String getEmail()
	+Collection<? extends GrantedAuthority> getAuthorities()
	+boolean isAccountNonExpired()
	+boolean isAccountNonLocked()
	+boolean isCredentialsNonExpired()
	+boolean isEnabled()
}

class CustomerDetailsService{
	-CustomerRepository customerRepository
	+CustomerDetails loadUserByUsername()
}

class Product{
  -float price
  -int stock
  -int serialNumber
  -String description
  -String name
  -String image
  -int categoryId
  -int deiveryTime

  +float getPrice()
  +int getStock()
  +int getSerialNumber()
  +String getDescription()
  +String getName()
  +String getImage()
  +int getCategoryId()
  +int getDeliveryTime()
  +void setPrice()
  +void setStock()
  +void setDescription()
  +void setSerialNumber()
  +void setName()
  +void setImage()
  +void setCategoryId()
  +void setDeliveryTime()
}

' class Order{
'   -Product[] products
'   -String dateOfPlaced
'   -String dateOfArrival
'   +String getDateOfPlaced()
'   +String getDateOfArrival()
'   +void getProducts()
'   +void setProducts()
'   +void setDateOfPlaced()
'   +void setDateOfArrival()
' }

' Customer o-- Product
' Product o-- Order

' Shopping cart
' TODO:Make a cart class and add products here
class ShoppingCartService{

  ' +void addProduct()
  +void getProductsInCart()
  +void removeProduct()
  +void checkoutCart()
  +void getTotal()
}

' Category
' This is is gonna be a table too
class Category{
  -int categoryId
  -String name
}

interface CategoryRepository{
  +Category findByName()
}

' TODO:Order class
' Order
class Order{
  -int orderId
  ' List of maps with product and quantity
  -List
  -int customerId
  -boolean deliveryStatus
  ' Make a method to calculate the max for delivery time
}

' TODO:Auth class
class AuthorizationController{
  +String register()
  +String login()
}

class ManagerController{
  -ManagerRepository managerRepository
  +void addItem()
  +void removeItem()
  +void getReport()
  ' how is the report being gotten?
  ' what will the difference be between the Product methods to update product attributes?
}

class AdminController{
    -AdminRepository adminRepository
    +void addManager()
    +void removeManager()
}
@enduml